### ISSUE TITLE
CONTROL_FLAG_AUTO_TASK flag does not send confirmation

### ISSUE THREAD

**Issue by ofiryakobian** [basecamelectronics/sbgc32-serial-api#8]
i tried to use the CONTROL_FLAG_AUTO_TASK but i don't receive confirmation i just get 1. --> CMD_CONTROL (#67): PROCESSED when i send the control

**Comment by qsivey** [comment]
Hello!
Did you command to gimbal to send confirmation after CMD_CONTROL? See example to the SBGC32_Contorl() function. 
Also note that you can chech the confirmation with the SBGC32_ExpectCommand() function.

**Comment by ofiryakobian** [comment]
Hi, this how I tried to put the flags:
        Control.mode[PITCH] = CtrlMODE_ANGLE | CtrlFLAG_AUTO_TASK;
        Control.mode[YAW] = CtrlMODE_ANGLE | CtrlFLAG_AUTO_TASK;
        Control.mode[ROLL] = CtrlMODE_ANGLE | CtrlFLAG_AUTO_TASK;
        SBGC32_Control(&SBGC32_Device, &Control);
        SBGC32_CheckConfirmation(&SBGC32_Device, &Confirm, CMD_CONTROL); 
and I get
 7. --> CMD_CONTROL (#67): PROCESSED 
8. <-- CMD_CONFIRM (#67): PROCESSED 

before I reached to the desired angles

**Comment by qsivey** [comment]
The fact is that the controller will always send the first confirmation command immediately to verify data accuracy. To receive confirmation of arrival at the destination angles, register an additional confirmation command. However keep in mind that working in the simplified blocking mode you are only able to adjust general RX timeout for all functions in the serialAPI_Config.h file. I advice you to try the non-blocking mode for our library with advanced serial function parameters. Also this way, you will be able to set a timeout for each command individually, not to mention gaining access to much broader functionality within the library. Learn more about this mode with the QuickStart examples.

**Comment by qsivey** [comment]
Hello!
Note that you leave Control.mode[PITCH] = CtrlMODE_ANGLE; without CtrlFLAG_AUTO_TASK parameter this time.
Also keep in mind that the timeout parameter for the second confirmation should approximately align with the time required for the camera to move to the designated point. Otherwise you may assign SCTimeout_MAX to this command but in this case you have a chance to stuck cause to the sbgcBlockQueue() macro if UART communication suddenly breaks. You can also avoid blocking the command queue and receive confirmation via a callback. How to create and use them is also described in the QuickStart example. You can fully unlock the potential of the library in OS mode, as only in this mode are all commands processed automatically in real time with interrupts.

I have slightly edited your code and attached a version that works correctly on my STM32F7.
You can verify that this is the required confirmation command by checking the cmdData field, which equals 1.
Additionally double check that the SBGC_NEED_CONFIRM_CMD is enabled.
Also note that the SCParam_FORCE_CALLBACK parameter is useful only when you assign a callback function to the command manually (like in the SBGC32_ReadRealTimeData4 above).

![{5CEB2A2C-701D-4F73-AE92-9CA0200C3E5E}](https://github.com/user-attachments/assets/1a4359ac-8462-4a4f-be81-062bfc1875cb)
![{7C5CB56F-C74A-47D3-9F15-7392A36163C9}](https://github.com/user-attachments/assets/450e03b5-49b2-41b0-8a9d-7b2a522fe4b6)
[control.txt](https://github.com/user-attachments/files/17394476/control.txt)
